### PR TITLE
Fix #222 : Migrate to sound null safety

### LINKED ISSUE #222: Migrate to sound null safety
Description:

- Migrate to sound null safety
- Bump up package version

### PR DESCRIPTION
**Pull request by figengungor**

### CODE REVIEW

**Comment by Klazyo** [comment]
Does it work with  null safe i am not used to Github .  
its the only package left for to migrate is it safe to migrate without changing  this package to null safe

**Comment by uttusharma** [comment]
> Does it work with null safe i am not used to Github .
> its the only package left for to migrate is it safe to migrate without changing this package to null safe

Nope you have to use null safety package 

in you pubspec.yaml use it like this : 

``` 
flutter_datetime_picker:
  git:
    url: https://github.com/figengungor/flutter_datetime_picker.git
 ```

**Comment by Klazyo** [comment]
> > Does it work with null safe i am not used to Github .
> > its the only package left for to migrate is it safe to migrate without changing this package to null safe
> 
> Nope you have to use null safety package
> 
> in you pubspec.yaml use it like this :
> 
> ```
>   flutter_datetime_picker:
>     git:
>       url: https://github.com/figengungor/flutter_datetime_picker.git
> ```

Thank you sir

**Comment by kalmigs** [comment]
When I try to "Cancel" or pressing outside the Date/Time picker bottom sheet it will cause an exception error.
I think "?" should be added to return types so it will not cause the said error:

```dart
// original code from flutter_datetime_picker.dart
static Future<DateTime> showDatePicker(
static Future<DateTime> showTimePicker(

// with changes
static Future<DateTime?> showDatePicker(
static Future<DateTime?> showTimePicker(
```

**Comment by figengungor** [comment]
Thanks @kalmigs. Fixed it.

**Pull request merged**
