### PR TITLE
Allow to disable a column in a layout + time picker optional seconds

### PR DESCRIPTION
**Pull request by martin-danhier**
Hello, it's me again^^

I noticed that a picker must have 3 columns, but in some case you may want only two (for example in a time picker without the seconds column). 
With this commit, setting a column's layout proportion to 0 will disable the column completely (without needing to do weird proportions like [100, 100, 1]).

That created an opportunity for a "showSecondsColumn" property in the TimePickerModel that would enable/disable the seconds column, so I implemented it too. :) Apparently, this is a feature that is requested by several people: #61 #45 

Finally, I fixed the warnings created by my previous commit.

Have a good day,

Martin

### CODE REVIEW

**Comment by patreu22** [comment]
+1 for this PR, any reason it's not merged yet?

**Comment by bagus-repository** [comment]
Please merge this if validated, it's very useful

**Comment by jsonthor** [comment]
I also need this feature. We don’t need the seconds feature for setting a notification time for example.

**Comment by Realank** [comment]
It look great, sorry for all for my late PR review, thanks

**Comment by Realank** [comment]
It looks great, sorry for all for my late PR review, thanks

**Comment by patreu22** [comment]
Great, thanks for merging that! Would it be possible to update the pub package as well? :)

**Comment by huitingyeong** [comment]
Hi like this feature. Is it possible to disable it from user modification but still display the current value?

**Pull request merged**
