### PR TITLE
Changed DiagnosticableMixin to Diagnosticable

### PR DESCRIPTION
**Pull request by ditheshthegreat**
There is a bug due to flutter upgrade DiagnosticableMixin to change Diagnosticable

### CODE REVIEW

**Comment by smit9612** [comment]
can we merge this PR?

**Comment by furkankurt** [comment]
@smit9612 you can use like that;
  

    flutter_datetime_picker:
      git:
        url: https://github.com/ditheshthegreat/flutter_datetime_picker # Repo
        ref: patch-1 # Branch name

Thank you @ditheshthegreat!

**Comment by nstrelow** [comment]
Please merge @Realank

**Comment by medyas** [comment]
@Realank can you merge this and update the plugin

**Comment by fnicastri** [comment]
should we fork the package?

**Comment by guohuanle** [comment]
Now the version after 1.20 is not available. The temporary solution is to modify the source code and change "DiagnosticableMixin" to "DiagnosticableTreeMixin" so that both the new version and the old version are available. I don’t know if this modification is correct, I hope to update the version as soon as possible (some people say it can be changed to "Diagnosticable", but this only solves the problem of the new version of the SDK, the old version of the SDK is not compatible)

**Comment by Realank** [comment]
Done

**Pull request closed without merging**
