### PR TITLE
Add basque language support

### PR DESCRIPTION
**Pull request by ibaiimaz**

### CODE REVIEW

**Comment by Realank** [comment]
Thanks for your support, I think you may missing a case for Basque in i18nObjInLocale method, please refer to other PRs to add it, thanks very much

**Comment by ibaiimaz** [comment]
I added the case for Basque in i18nObjInLocale method just before default case. I was not sure if I need to order it alphabetically because apparently no order was used, so I put it in the last position.

Looking to others PRs I realized I did not edit README so I did. Let me know if something else is missing. Thanks.

**Comment by Realank** [comment]
Sorry, I can't see the 'eu' case in i18nObjInLocale in PR, however, I added it in this PR, so Basque has been merged ,thanks for your support

**Comment by ibaiimaz** [comment]
You were right, I forgot to commit the change. My fault. Thanks very much for all

**Pull request merged**
