### PR TITLE
Realank#197 shadowThemeOnly is removed on flutter master

### PR DESCRIPTION
**Pull request by espresso3389**
Refs #197;
flutter/flutter#69050 recently removed Theme.of(context, shadowThemeOnly) and it recommends to use `InheritedTheme.capture` for applying shadowing-themes to widgets. Although `InheritedTheme.capture` is not available on stable/beta channel, we can still use `InheritedTheme.captureAll` for the purpose.

### CODE REVIEW

**Comment by GreenLim** [comment]
Great work, I tried your patch, works perfect for me.

**Comment by nstrelow** [comment]
Please merge soon if possible :D

**Comment by nstrelow** [comment]
@Realank Could you please merge this? It is still not fixed.
Thanks a lot

**Comment by syonip** [comment]
Can you please merge?

**Comment by nstrelow** [comment]
@Realank You can also merge this one?
Just one of them please!

**Review by lukee1234 — APPROVED** [review]

**Comment by nstrelow** [comment]
Great fix @espresso3389. ありがとうございます

@Realank Please merge or let us help you maintain the repository :)

**Review by srihamat — APPROVED** [review]
👍

**Review by nstrelow — APPROVED** [review]

**Pull request merged**
