### PR TITLE
Added a minTime and maxTime parameter to the DateTimePicker

### PR DESCRIPTION
**Pull request by kevinsallee**

### CODE REVIEW

**Comment by kevgug** [comment]
I think this is essential to the date-time picker @kevinsallee. 

Perhaps the date-only picker should receive a similar update. I believe it should look more similar to the date-time picker than the current one. 

This can likely be achieved by duplicating your commit and simply removing the time-related code.

**Current**:
- slightly confusing
image

**Proposed**:
- simpler design (at least option to choose between old/new mode)

untitled-1

Thanks,
Kevin

**Comment by kevinsallee** [comment]
The model picked always has three columns, and it should be easily adaptable to the date picker. But the change your asking for is bigger since it's not z three column model. It's a one column model which would be easily implementable but it's beyond the scope of this request

**Comment by kevgug** [comment]
> The model picked always has three columns, and it should be easily adaptable to the date picker. But the change your asking for is bigger since it's not z three column model. It's a one column model which would be easily implementable but it's beyond the scope of this request

I understand, and also single column is likely wrong thing to do. Will see if I can create a separate PR to sort out the format.

**Comment by thorbenPollack** [comment]
Great job! @kevinsallee 
Can this get merged into the master branch?

**Comment by kevinsallee** [comment]
@thorbenPollack I wish but I can't.  Only those with write access can.

**Comment by Realank** [comment]
As I mentioned before, (maxTime.day - minTime.day) cannot generate all the days, if maxTime and minTime are in different year. and it will cause bug

**Comment by Realank** [comment]
hi, your PR has side effect, I've added minTime / maxTime for date time picker as an optional parameter, please have a try. still thanks for your PR

**Pull request closed without merging**
